### ISSUE TITLE
[id 2926, 2242, 2246, 2247, 2586] wrong npc orientation

### ISSUE THREAD

**Issue by schnek** [AscEmu/OneDB#13]
all id2242 fly
![wowscrnshot_050618_144607](https://user-images.githubusercontent.com/1216225/39673176-f731ce24-513f-11e8-8e08-5de5372f49da.jpg)
![wowscrnshot_050618_144520](https://user-images.githubusercontent.com/1216225/39673193-6ae7d5f2-5140-11e8-928f-088beb56f950.jpg)

all id2926 fly
![1](https://user-images.githubusercontent.com/1216225/39673531-047cf62e-5147-11e8-88af-83a133a6e52a.jpg)

**Comment by Zyres** [comment]
issues please to AscEmu/AscEmu
