### ISSUE TITLE
[id 2097] dead npc attacking

### ISSUE THREAD

**Issue by schnek** [AscEmu/OneDB#14]
![wowscrnshot_050618_172319](https://user-images.githubusercontent.com/1216225/39674313-9bea74a4-5152-11e8-8e7e-03f64d437c40.jpg)

![wowscrnshot_050618_173015](https://user-images.githubusercontent.com/1216225/39674357-340e0b1a-5153-11e8-94aa-2252a6499f6d.jpg)

**Comment by Zyres** [comment]
core problem
