### ISSUE TITLE
npc id 620 chicken

### ISSUE THREAD

**Issue by schnek** [AscEmu/OneDB#16]
npc has the wrong flag. the correct flag is neutral.

https://ascemu.github.io/Wiki/database/world/creature_properties/#faction

according to the wiki, the flag should be
`7    = Neutral`

http://www.wowhead.com/npc=620/chicken
`UPDATE `creature_properties` SET `faction`='7' WHERE  `entry`=620 AND `build`=5462;`

![wowscrnshot_050618_123323](https://user-images.githubusercontent.com/1216225/39671911-d0f69426-5129-11e8-8667-5b7f87ac687e.jpg)

**Comment by Zyres** [comment]
#close in https://github.com/AscEmu/AscEmu/tree/bb0cd555aab60232f2475bb987c90fceb2597471
